SPARK_MODE = "local[*]"
INPUT_SUNEDU_PATH = "resources/data/csv/sunedu.csv"
INPUT_RISK_PATH = "resources/data/csv/risk.csv"
OUTPUT_PATH = "resources/data/output"
OVERWRITE = "overwrite"
HEADER = "header"
INFER_SCHEMA = "inferSchema"
